### PR TITLE
fix #199 limit the left size of the return button

### LINKED ISSUE #199: [Frontend] limit the left size of the return button
Today when the client is using a big screen the return button go to extreme left. we need to limit it to stay in the same line of the "EconoFlow" brand of the navbar.

### PR DESCRIPTION
**Pull request by Dan-613**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization

## Related Tickets & Documents

- Related Issue #
- Closes #199 

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [X] No, and this is why: Changes only affected layout
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by Dan-613** [comment]
@FelipePSoares When you get a moment, please take a look at the changes. Although I've been developing for over 20 years, it's the first time I've contributed to a project on Github.

**Comment by FelipePSoares** [comment]
Thank you so much for choose my project. I'm developing for 12 years. It's the first time that I make my own project in git hub. The others is just small one for test something. This one I'm really using. Thank you.

I'll take a look as soon as possible.

**Comment by FelipePSoares** [comment]
Hi, 

I was thinking now, what do you think to change in the project details to keep the date above also, as in the other pages?
like here for example, I know that it's not you that make it. but I think now that maybe keep the pattern would be better.

image

image

**Comment by Dan-613** [comment]
> Hi,
> 
> I was thinking now, what do you think to change in the project details to keep the date above also, as in the other pages? like here for example, I know that it's not you that make it. but I think now that maybe keep the pattern would be better.
> 

@FelipePSoares I agree. The only reason I didn't move it in this edit is that it wasn't specifically related to the issue being committed.

**Comment by FelipePSoares** [comment]
Feel free to do or propose modification if you see something. I really thank you for your help.

**Comment by Dan-613** [comment]
@FelipePSoares If you are happy with the code changes in this pull request, please can you do the honours of approving it. I dont want to accept anything and accidentally break/delete something 🙈

**Review by FelipePSoares — APPROVED** [review]

**Comment by FelipePSoares** [comment]
@Dan-613 Merged. Thank you again, for your help. It's already running now the master pipeline in a few minutes will be on production.

**Pull request merged**
