### PR TITLE
Feat: changed delete user to be token-based confirmation

### LINKED ISSUE #277: [Backend] Change deletion endpoint to be token-based confimation
Account deletion is a significant action that requires confirmation to prevent accidental or unauthorized deletions. To handle this securely, we will implement a token-based confirmation process.

Steps to Implement:
1. First Request: Initiate Account Deletion:
   - When a user initiates account deletion by calling the `DELETE /api/account` endpoint, the system will:
      - Generate a JWT token containing essential information, such as:
``` json
{
    "userId": "12345",
    "action": "confirm_delete",
    "exp": 1700000000
}
```
- Return a response with a confirmation message and the token.
- Request example:
``` http
DELETE /api/account
---
202 Accepted
{
    "confirmationMessage": "You are associated as an administrator with one or more projects. Please transfer the administration to another user before deleting your account. Otherwise, the project(s) will be deleted.",
    "confirmationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
}
```

2. Second Request: Confirm Deletion with Token
   - The user must confirm the account deletion by making a second request, including the `confirmationToken` received in the first step.
``` http
DELETE /api/account?confirmationToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
---
200 OK
```
- Behavior:
   - Validate the token:
      - Ensure it is valid and has not expired.
      - Confirm the `action` field is set to `confirm_delete`.
   - If validation passes, proceed with the account deletion.
   - If validation fails, return a `401 Unauthorized` response

### PR DESCRIPTION
**Pull request by FelipePSoares**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization

## Description

Change the user delete logic to be token-based confirmation.

## Related Tickets & Documents

- Related Issue #277 
- Closes #277 

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27!

When you have some time, can you check if this logic is right and will be enough for your implementation, please, feel free to recommend and suggest any modification.

Thank you in advance.

**Comment by saksham-malhotra-27** [comment]
@FelipePSoares Ya, I checked and it looks perfect to me, 
Just a thing that I noticed that you’ve added the token generator in the delete API. Have you also implemented an API to confirm if the user is an admin, or does it directly show a warning about being an admin before deleting the account?

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27 

The process will work like that, to delete a user we need to call twice the same endpoint:
First call you will receive a `confirmationMessage` and a `confirmationToken`: 
``` http
DELETE /api/account
---
202 Accepted
{
    "confirmationMessage": "This message will change based on user",
    "confirmationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
}
```
This `confirmationMessage` should be showed to the user, this message changes based if the user is admin or not of some project.

The Second call is to confirm the delete:
``` http
DELETE /api/account?confirmationToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
---
200 OK
```

You will call the same endpoint but now sending the `confirmationToken` as query parameter.

Do you got it?

**Comment by saksham-malhotra-27** [comment]
@FelipePSoares Yes, I understand your point. The work is perfect; however, I would suggest the following:
**Preferred Approach**: Pass the token in the request body.
```
{
    "confirmationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
}
```
**Reason**: Passing the token in the request body is more secure because it prevents the token from being exposed in logs, browser history, or bookmarks. Unlike query parameters, which are part of the URL and might be unintentionally logged by servers or shared in URLs, the request body remains private and is less likely to be exposed. This approach ensures better security and reduces the risk of accidental token leakage.

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27

I make the change, can you confirm that is everything OK now.

Thank you for your suggestion.

**Comment by saksham-malhotra-27** [comment]
Yup @FelipePSoares ! Good to go

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27

If you know how to do it you can approve the review. Than it will merge Automatically.

Otherwise I can do it later.

**Review by saksham-malhotra-27 — APPROVED** [review]
Great Approach of token based deletion !

**Comment by FelipePSoares** [comment]
Thanks

**Pull request merged**
