### PR TITLE
Feature/#257 update login page to use angular material

### PR DESCRIPTION
**Pull request by ahmedhalac**
Update login/register page to use angular material

Related to #257

### CODE REVIEW

**Comment by FelipePSoares** [comment]
Hi @ahmedhalac,

Some tests failed but it's simple, it's just because you changed the id from username to email, maybe the best to fix it here is remove this id at all and change on cypress test to select the field by formControlName. 

You can use this selectors `input[formControlName=email]` and `input[formControlName=password]` instead `#username` and `#password`

**Comment by FelipePSoares** [comment]
Hi @ahmedhalac ,

Sorry man, you forgot to change on register, the last one and the test will pass.

**Comment by ahmedhalac** [comment]
Hi @FelipePSoares. I already fixed register page test. Now it passed successfully.

**Review by FelipePSoares — APPROVED** [review]

**Comment by FelipePSoares** [comment]
Hi @ahmedhalac ,

Thank you so much again.

**Pull request merged**
