### PR TITLE
fix: change input type of amount and budget fields to number (#256)

### LINKED ISSUE #256: [Frontend] Change amount fields to type="number"
Change amount fields to type="number", taking care to be possible to add decimal values on amount fields and just integers on budget fields.

### PR DESCRIPTION
**Pull request by AmirAbdollahi**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization

## Related Tickets & Documents

- Related Issue #256
- Closes #256 

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] Yes
- [ ] No, and this is why: 
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by AmirAbdollahi** [comment]
Oh, it seems some tests have failed, and I think my changes were the cause.

**Comment by FelipePSoares** [comment]
@AmirAbdollahi ,

Yes, but no problem, you can run the tests locally easily. just run the application as usual and than go the folder 'easyfinance.client' and run the command `npx cypress open`. Then you can run the tests and see step by step what happen. Maybe just need to change something in the tests.

Let me know if you need some help.

**Comment by FelipePSoares** [comment]
@AmirAbdollahi 

I modified the [contributing.md](https://github.com/FelipePSoares/EconoFlow/blob/master/.github%2FCONTRIBUTING.md) to have more detail how to run the tests. If you need help to analyze them, just let me know.

**Comment by AmirAbdollahi** [comment]
> @AmirAbdollahi
> 
> I modified the [contributing.md](https://github.com/FelipePSoares/EconoFlow/blob/master/.github%2FCONTRIBUTING.md) to have more detail how to run the tests. If you need help to analyze them, just let me know.

Sure! Thank you very much. @FelipePSoares

**Comment by AmirAbdollahi** [comment]
> @AmirAbdollahi
> 
> I modified the [contributing.md](https://github.com/FelipePSoares/EconoFlow/blob/master/.github%2FCONTRIBUTING.md) to have more detail how to run the tests. If you need help to analyze them, just let me know.

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi, 

I saw that you comment empty. Can I help you with something?

**Comment by AmirAbdollahi** [comment]
> Hi @AmirAbdollahi,
> 
> I saw that you comment empty. Can I help you with something?

Oh, I'm sorry. That was a small mistake on my part.

**Comment by FelipePSoares** [comment]
@AmirAbdollahi ok, no problem, just asking if you need something, but if everything is fine, good. 

Have a nice day.

**Comment by AmirAbdollahi** [comment]
I'm so thrilled to see all the tests are green.

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi,

I found some issues in specific languages and browser, but don't worry about that, thank you for your help, I'm working on your branch changing some details, when I finish it I'll update this MR with this changes and I advice you to check. 

Sorry for not approve yet. But you make a good job, just some small points that I don't thing when I wrote the issue. hahaha

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi ,

After a lot of study and errors. kkk I finally find a solution for the problem, but unfortunately I need to change from `type="number"` to `type="text"` again, because when it's `type="number"` the navigator just send the value when is a valid number, otherwise it send null and null in this situation is a valid value, because you can create a expense just with budget without value. 

I will apply now the solution for the others forms, but I think that this way with `inputmode="decimal"` and validation based on user's language will be the best solution.

Thank you a lot and sorry to create a issue to put `type="number"` and now make it different, I really believed that `type="number"` was the best solution, but, no.

**Comment by FelipePSoares** [comment]
@AmirAbdollahi ,

No it's perfect, it's my fault, I'll finish now this issue. The other one that you are working on will be so helpful also. Thank you

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi,

Finally I finished it. If you want to see what I did you can see in the changes. Now I'll just wait you finish yours to avoid conflits and then I apply this for edit forms also. 

Thank you for your help again.

**Comment by AmirAbdollahi** [comment]
> Hi @AmirAbdollahi,
> 
> Finally I finished it. If you want to see what I did you can see in the changes. Now I'll just wait you finish yours to avoid conflits and then I apply this for edit forms also.
> 
> Thank you for your help again.

Thank you very much @FelipePSoares . 
Ok. I'll try to finish it tonight.

**Comment by AmirAbdollahi** [comment]
Resolving conflicts ...

**Comment by AmirAbdollahi** [comment]
> Resolving conflicts ...

Hi @FelipePSoares,
Merge conflicts have been resolved. Please review the changes again before merging the branch.

**Comment by FelipePSoares** [comment]
Ok thanks

**Comment by FelipePSoares** [comment]
@AmirAbdollahi, 

I need to apply the changes to the edit forms that you worked also.

**Review by FelipePSoares — APPROVED** [review]

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi,

Finally we finalized this issue. thanks you for your help.

**Pull request merged**
